### ISSUE TITLE
New update ruining it

### ISSUE THREAD

**Issue by felipe4000** [DarkSnakeGang/GoogleSnakeCustomMenuStuff#47]
The new update for the mods introduced some new icons. But now, sometimes the mods don't work, and the once-large maps are now all the same size. What has happened?

**Comment by carlgustavh** [comment]
I can confirm that this is an issue. To recreate this is my bookmarklet:
`javascript: req = new XMLHttpRequest(); req.open('GET', 'https://raw.githubusercontent.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/main/custom.js%27); req.onload = function() { eval(this.responseText + 'snake.more_menu();'); }; req.send();`
No idea why because i've looked at the commits and i've only changed the image sources. It shouldn't have affected gameplay.

**Comment by carlgustavh** [comment]
https://user-images.githubusercontent.com/95967108/146172799-55e9ddf4-8106-47a2-af6d-60f8ebfb7cb4.mp4

**Comment by carlgustavh** [comment]
It's fixed now.
